"""
Schemas package — Data Transfer Objects for the RAG Engine.

All inter-module data is exchanged via these Pydantic models.
No business logic. Schema definitions only.
"""

from rag_engine.schemas.document import Document, DocumentMetadata, DocumentLifecycleState
from rag_engine.schemas.chunk import Chunk, ChunkMetadata, ChunkHierarchy, ChunkStatistics
from rag_engine.schemas.embedding import (
    EmbeddingVector,
    EmbeddingRequest,
    EmbeddedChunk,
    EmbeddingBatchRequest,
    EmbeddingBatchResponse,
    EmbeddingMetrics,
    compute_vector_checksum,
)
from rag_engine.schemas.citation import Citation, Source
from rag_engine.schemas.retrieved_document import RetrievedDocument, ScoredChunk
from rag_engine.schemas.parsed_document import (
    CitationCoordinates,
    CleaningStatistics,
    CleanParsedDocument,
    CrossReference,
    DocumentStatistics,
    DrawingMetadata,
    EntityGraph,
    EntityRelationship,
    EquipmentEntity,
    EquipmentType,
    PageMapEntry,
    ParsedDocument,
    ParsedMetadata,
    RelationType,
    SafetyWarning,
    SafetyWarningSeverity,
    Section,
    Table,
    TableCell,
    ValidationIssue,
    ValidationReport,
)

__all__ = [
    "Document",
    "DocumentMetadata",
    "DocumentLifecycleState",
    "Chunk",
    "ChunkMetadata",
    "ChunkHierarchy",
    "ChunkStatistics",
    "EmbeddingVector",
    "EmbeddingRequest",
    "EmbeddedChunk",
    "EmbeddingBatchRequest",
    "EmbeddingBatchResponse",
    "EmbeddingMetrics",
    "compute_vector_checksum",
    "Citation",
    "Source",
    "RetrievedDocument",
    "ScoredChunk",
    "ParsedDocument",
    "CleanParsedDocument",
    "CleaningStatistics",
    "PageMapEntry",
    "Section",
    "Table",
    "TableCell",
    "EquipmentEntity",
    "EquipmentType",
    "EntityRelationship",
    "RelationType",
    "EntityGraph",
    "SafetyWarning",
    "SafetyWarningSeverity",
    "CrossReference",
    "DrawingMetadata",
    "ParsedMetadata",
    "DocumentStatistics",
    "ValidationIssue",
    "ValidationReport",
    "CitationCoordinates",
    # Milestone 7: Vector Store Schemas
    "DistanceMetric",
    "PayloadSchemaType",
    "FilterOperator",
    "FieldFilter",
    "MetadataFilter",
    "ScoredVectorChunk",
    "IndexingResult",
    "DiffPlan",
    "CollectionStats",
    "CollectionVersionInfo",
    "VersionDiffReport",
    "MigrationReport",
    "PayloadIndexHealthReport",
    "OptimizationMetrics",
    "CompleteOptimizationReport",
    "VectorDBHealthReport",
    "StorageStatsReport",
    # Milestone 9: Prompt Schemas
    "RetrievedPrompt",
    "PromptPayload",
    "SystemPrompt",
    "ContextWindow",
    "ConversationTurn",
    "PromptValidationResult",
]

from rag_engine.schemas.vector_store import (
    DistanceMetric,
    PayloadSchemaType,
    FilterOperator,
    FieldFilter,
    MetadataFilter,
    ScoredVectorChunk,
    IndexingResult,
    DiffPlan,
    CollectionStats,
    CollectionVersionInfo,
    VersionDiffReport,
    MigrationReport,
    PayloadIndexHealthReport,
    OptimizationMetrics,
    CompleteOptimizationReport,
    VectorDBHealthReport,
    StorageStatsReport,
)

from rag_engine.schemas.prompt import (
    ContextWindow,
    ConversationTurn,
    PromptPayload,
    PromptValidationResult,
    RetrievedPrompt,
    SystemPrompt,
)
